config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  post 'blacklist_users/create'
  get 'blacklist_users/edit'
  get 'blacklist_users/learn'
  delete 'blacklist_users/destroy'

  devise_for :users
  get 'users/options'
  patch 'users/update'

  get 'dashboard', to: "pages#dashboard", as: :dashboard
  get 'blockedwebsite', to: 'pages#blockedwebsite', as: :blockedwebsite
  get 'forms', to: "pages#forms", as: :forms
  get 'plans/index'
  resources :flashcards, only: [:show]
  resources :flashcard_users, only: [:create]
  resources :blacklists, only: [:destroy, :create]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'login_return_token', to: 'tokens#login_return_token'
      resources :blacklists, only: [ :index ]
      patch 'blacklists/create', to: 'blacklists#create'
      post 'blacklists/signup', to: 'blacklists#signup'
      resources :flashcards, only: [ :index, :show, :update ]
    end
  end

end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :category
  has_many :flashcard_users
  has_many :users, through: :flashcard_users
end

app/controllers/api/v1/flashcards_controller.rb
class Api::V1::FlashcardsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User
  before_action :set_flashcard, only: [ :show, :update ]

  def index
    @flashcards = policy_scope(Flashcard)
    authorize @flashcards

    user_email = request.env["HTTP_X_USER_EMAIL"]
    user = User.find_by(email: user_email)

    flashcard_users = user.flashcard_users
    not_completed = flashcard_users.where(completed: false)
    @flashcards = not_completed.map do |flashcard_user|
      flashcard_user.flashcard
    end

    @flashcards = @flashcards.shuffle.first(3)
  end

  def show
  end

  def update
    # binding.pry
    user_email = request.env["HTTP_X_USER_EMAIL"]
    user = User.find_by(email: user_email)

    @flashcard_user = FlashcardUser.find_by(user_id: user.id, flashcard_id: @flashcard.id)
    @flashcard_user.completed = true
    @flashcard_user.save
    render :show
  end

  private

  def set_flashcard
    @flashcard = Flashcard.find(params[:id])
    authorize @flashcard
  end

  def flashcard_params
    params.require(:flashcard).permit(:id, :question, :answer, :completed)
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def show
    @user = current_user
    @current_flashcard = FlashcardUser.where(user_id: @user.id).where(completed: false).first.flashcard
    @next_flashcard = Flashcard.find(params[:id].to_i + 1)
  end
end

app/views/flashcards/show.html.erb
<div class="flashcard-container">

  <div class="flashcard-category">
    <%= image_tag "rails-logo.svg", alt: "Rails logo" %>
  </div>

  <div id="question">
    <%= @current_flashcard.question %>
  </div>

  <textarea class="user-answer" rows="4" placeholder="Enter your answer here"></textarea>

  <button class="tablinks" data-id="Answer">Find Answer</button>

  <div id="Answer" class="tabcontent d-none">

    <div class="box">
      <div id="question"><p style="padding-left: 5px;"><%= @current_flashcard.answer %></p></div>
    </div>

    <div style="text-align: center;">

      <!-- ADD HIDDEN DATA FIELD WITH COUNT OF FLASHCARDS -->

      <%#= link_to "Next Question", flashcard_users_path(flashcard_id: @flashcard.id), method: :post, class: "btn btn-info btn-xs" %>
      <%= link_to "Next Question", flashcard_path(@next_flashcard), class: "btn btn-info btn-xs", id: "next-btn"%>
    </div>
  </div>
</div>


<!-- <div style="text-align: center; padding-top: 30px;">
<h2> Congratulations you have done your flashcards </h2>
</div>
<div style="text-align: center; padding-top: 30px;">
  <%= image_tag get_random_image %>
</div>
<div style="text-align: center; padding-top: 30px;">
<%#= link_to "Go to next Question", flashcard_path(@flashcard.id + 1), class: "btn btn-info btn-xs" %>
<button class="btn btn-info btn-xs"> <a href="https://facebook.com" target="_blank"> Go to your blocked website </a> </button>
</div> -->