config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  post 'blacklist_users/create'
  get 'blacklist_users/edit'
  get 'blacklist_users/learn'
  delete 'blacklist_users/destroy'

  devise_for :users
  get 'users/options'
  patch 'users/update'

  get 'dashboard', to: "pages#dashboard", as: :dashboard
  get 'blockedwebsite', to: 'pages#blockedwebsite', as: :blockedwebsite
  get 'forms', to: "pages#forms", as: :forms
  get 'plans/index'
  resources :flashcards, only: [:show]
  resources :flashcard_users, only: [:create]
  resources :blacklists, only: [:destroy, :create]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'login_return_token', to: 'tokens#login_return_token'
      resources :blacklists, only: [ :index ]
      patch 'blacklists/create', to: 'blacklists#create'
      post 'blacklists/signup', to: 'blacklists#signup'
      resources :flashcards, only: [ :index, :show, :update ]
    end
  end

end

app/views/pages/blockedwebsite.html.erb
<div class="new-blacklist-page-container">

  <div class="new-blacklist-form">

    <h3 class="page-subtitle">Add another blacklisted website...</h3>

      <%= simple_form_for @blacklist, url: blacklists_path, method: :post do |f| %>

        <div class="form-inputs">
          <%= f.input :website_name, required: true, autofocus: true, label: "Name:" %>
          <%= f.input :website_url, required: true, autofocus: true, label: "Url:" %>
        </div>

        <div class="new-blacklist-btn-container">
          <%= f.button :submit, "Blacklist website", class: "btn-ghost" %>
        </div>
      <% end %>

  </div>

</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-page-container">
  <div class="dashboard-container">

    <h1 class="page-title">Your dashboard....</h1>

    <h3 class="page-subtitle">Your blacklisted websites</h3>

    <div class="blacklisted-websites-container">
      <% @user.blacklists.each do |blacklist| %>
        <div class="blacklist-card">
          <p><%= blacklist.website_name.capitalize() %></p>

          <!-- Needs to delete BlacklistUser not Blacklist -->

          <%#= link_to blacklist_users_destroy_path(@user, blacklist), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= link_to blacklist_path(blacklist),method: :delete, data: { confirm: 'Are you sure?' } do %>

            <i class="fas fa-minus-circle"></i>
          <% end %>
        </div>
      <% end %>

      <div class="dashboard-btn-container">
        <a href="/blockedwebsite" class="btn-ghost">
          <p>Add another website</p>
          <i class="fas fa-plus-circle"></i>
        </a>
      </div>
    </div>

    <h3 class="page-subtitle">Your learning topics</h3>

    <div class="learning-topics-container">
      <div class="learning-topic-card">
        <p><%= @learning_topic %></p>
        <i class="fas fa-minus-circle"></i>

      </div>

      <div class="dashboard-btn-container">
        <a href="#" class="btn-ghost">
          <p>Add another learning topic</p>
          <i class="fas fa-plus-circle"></i>
        </a>
      </div>
    </div>
    <div class="download-button">
    <a class= "btn btn-ghost" href="https://github.com/jonasvanbuel/holdthatthought-extension" target='_blank'> Download</a>
    </div>
  </div>
</div>

app/views/pages/forms.html.erb
<section>
  <div class= "page2">
    <div class= "form-1 align-items-center" id= "form-1" style = "padding-top: 150px; margin-bottom: 30px;">
      <div>
        <h3>What would you like to learn?</h3>
      </div>
      <div class= "card-container">
        <div class="card-product" id="card" >
          <%= image_tag "lewagon_logo.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>Le Wagon</h2>
            <p>Change your life, learn to code</p>
          </div>
        </div>
        <div class="card-product" id="card">
          <%= image_tag "duo.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>Duo Lingo</h2>
            <p>The worlds best way to learn a language</p>
          </div>
        </div>
        <div class="card-product" id="card">
          <%= image_tag "elevate.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>Elevate</h2>
            <p>Stay sharp, build confidence, and boost productivity</p>
          </div>
        </div>
      </div>
      <div class= "arrow">
        <a href="javascript:SwapDivsWithClick('form-1','form-2')" class="fas fa-arrow-right"></a>
      </div>
    </div>
 </div>
</section>

<!-- new blacklist form -->

<div class= "container" id="form-2" style= "display:none; transition: all 5s ease; margin-bottom: 30px; text-align: center;">
    <div class= "form-2 align-items-center" id= "form-2" style = "padding-top: 150px; margin-bottom: 30px;">
      <div>
        <h3>What would you like to avoid?</h3>
      </div>
      <div class= "card-container">
        <div class="card-product" id="card" >
          <%= image_tag "instagram.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>Instagram</h2>
            <!-- <p>Change your life, learn to code</p> -->
          </div>
        </div>
        <div class="card-product" id="card">
          <%= image_tag "facebook.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>Facebook</h2>
            <!-- <p>The worlds best way to learn a language</p> -->
          </div>
        </div>
        <div class="card-product" id="card">
          <%= image_tag "bbcnews.png", alt: "alttext" %>
          <div class="card-product-infos">
            <h2>BBC News</h2>
            <!-- <p>Stay sharp, build confidence, and boost productivity</p> -->
          </div>
        </div>
      </div>

    </div>
</div>



<!-- swap divs JS function -->

<script type="text/javascript">
function SwapDivsWithClick(div1,div2)
{
   d1 = document.getElementById(div1);
   d2 = document.getElementById(div2);
   if( d2.style.display == "none" )
   {
      d1.style.display = "none";
      d2.style.display = "block";
   }
   else
   {
      d1.style.display = "block";
      d2.style.display = "none";
   }
}
</script>

app/views/pages/home.html.erb
 <link rel="shortcut icon" href="#" <meta charset="UTF-8">
<header class = "video d-flex align-items-center justify-content-center">
  <div class="jumbotron jumbotron-fluid">
    <div class ="overlay">
      <%= video_tag "homepagevid.mp4",autoplay: true, loop: true, muted: 'muted', :controls => false, :id => 'jumbo-video-home', class: "tesben" %>
    </div>
  </div>
  <div class="intro-text">
   <div class="front-title">
   <h1> Waste your time productively </h1>
    <% if user_signed_in? %>
      <a class= "btn btn-ghost" href="/dashboard">Dashboard</a>
      <a class= "btn btn-ghost" href="https://github.com/jonasvanbuel/holdthatthought-extension" target='_blank'>Download</a>
    <% else %>
      <a class= "btn btn-ghost" href="/users/sign_up">Get Started</a>
    <% end %>
    </div>
  </div>
</header>

<div class="home-bottom">
    <div class="left-home">
      <%= image_tag "homeimage2.jpg", alt: "alttext" %>
    </div>
    <div class="right-home">
        <h2>Hold That Thought... is a browser extension to remind you to spend a few moments learning a topic of your choice, before allowing you access to the websites you're seeking to avoid</h2>
        <h2>Simply login, manage your list of blacklisted websites and leaning topics online, download our browser extension, and let us do the rest!</h2>
        <div style="text-align: right; padding-top: 20px;">
        <% if user_signed_in? %>
        <a class= "btn btn-ghost" href="https://github.com/jonasvanbuel/holdthatthought-extension" target='_blank'> Download</a>
        <% else %>
        <a class= "btn btn-ghost" href="/users/sign_up">Get Started</a>
        <% end %>
        </div>
    </div>
</div>


<!--
<script>

  const bgChanger = () => {
 if(window.scrollY > window.innerHeight / 3 ) {
  document.querySelector(".textbox").classList.remove("d-none");
  document.querySelector(".video").classList.add("d-none")
 } else {
  document.querySelector(".video").classList.remove("d-none");
  document.querySelector(".textbox").classList.add("d-none");

 }
}

window.addEventListener("scroll", bgChanger);
</script> -->

<!-- window.innerHeight / 3 -->

app/views/pages/learning.html.erb
<div class="new-blacklist-page-container">

  <div class="new-blacklist-form">

    <h3 class="page-subtitle">Add another learning topic</h3>

      <%= simple_form_for @blacklist, url: blacklists_path, method: :post do |f| %>

        <div class="form-inputs">
          <%= f.input :website_name, required: true, autofocus: true, label: "Name" %>
          <%= f.button :submit, "Blacklist website", class: "btn-ghost" %>
        </div>
      <% end %>

  </div>

</div>

app/views/pages/payment.html.erb
<h2 style="text-align: center; margin-top: 20px"> Hold That Thought Plan Options </h2>

<div style="text-align: center;">
<div class="cards">
  <div class="card-category" style="background-color: white;">
    <h2 style="margin-top: 30px;">Free Plan</h2>
    <div class="payment">
    <p> Websites Blocked: 2 </p>
    <p> Flashcards: 100 </p>
    <p> Learning Topics: 2 </p>
    <p style="margin-bottom: 20px;"> Cost: Free </p>
    <%= link_to "Use Free Plan", dashboard_path, class: "btn btn-info btn-xs" %>
    </div>

  </div>

  <div class="card-category" style="background-color: white;">
    <h2 style="margin-top: 30px;"> Medium Plan</h2>
    <div class="payment">
    <p> Websites Blocked: 5 </p>
    <p> Flashcards: 1000 </p>
    <p> Learning Topics: 5 </p>
    <p style="margin-bottom: 20px;"> Cost: £0.99 per month </p>
    <%= link_to "Use Medium Plan", dashboard_path, class: "btn btn-info btn-xs" %>
    </div>
  </div>

  <div class="card-category" style="background-color: white;">
    <h2 style="margin-top: 30px;"> Full Plan</h2>
    <div class="payment">
    <p> Websites Blocked: Unlimited </p>
    <p> Flashcards: Unlimited </p>
    <p> Learning Topics: Unlimited </p>
    <p style="margin-bottom: 20px;"> Cost: £4.99 per month </p>
    <%= link_to "Use Full Plan", dashboard_path, class: "btn btn-info btn-xs" %>
    </div>
  </div>
</div>
</div>

app/views/pages/sign_up.html.erb
<section>
   <div class= "page2">

      <div class= "form-1 align-items-center" id= "form-1" style = "padding-top: 150px; margin-bottom: 30px;">
         <div class= "title">
            <h3>What would you like to learn?</h3>
         </div>
              <div class= "card-container">
                <div class="card-product" id="card" >
                  <%= image_tag "logo.png", alt: "alttext" %>
                  <div class="card-product-infos">
                    <h2>Le Wagon</h2>
                    <p>Change your life, learn to code</p>
                </div>
            </div>

            <div class="card-product" id="card">
              <%= image_tag "duo.png", alt: "alttext" %>

              <div class="card-product-infos">
                <h2>Duo Lingo</h2>
                <p>The worlds best way to learn a language</p>
              </div>
            </div>

            <div class="card-product" id="card">
                <%= image_tag "elevate.png", alt: "alttext" %>

                <div class="card-product-infos">
                  <h2>Elevate</h2>
                   <p>Stay sharp, build confidence, and boost productivity</p>
                </div>
            </div>
        </div>
           <div class= "arrow">
            <a href="javascript:SwapDivsWithClick('form-1','form-2')" class="fas fa-arrow-right"></a>
       </div>
    </div>
 </div>
</section>


<!-- blacklist form -->


<div class= "container" id="form-2" style= "display:none; transition: all 5s ease; margin-bottom: 30px; text-align: center;">

<div class = "row">
  <div class= "col" id= "title" style= "padding-bottom: 40px; padding-top: 150px;">
  <h3 style= "text-align: center;">What would you like to avoid?</h3>

</div>
</div>

  <%= simple_form_for(@user, url: users_update_path, method: :patch) do |f| %>

    <div class="form-group">
      <input type="hidden" name="user[blacklist_ids][]" value="">
      <div class="blacklist-choices m-0">
        <% Blacklist.all.each do |blacklist| %>
          <input type="checkbox" class="hidden" value="<%= blacklist.id %>" name="user[blacklist_ids][]" id="user_blacklist_ids_<%= blacklist.id %>">
          <label for="user_blacklist_ids_<%= blacklist.id %>">
            <div class = "blacklist-all">
              <div class="blacklist-card" id= "blacklist-card">
                <%= image_tag blacklist.image_url, alt: "alttext" %>
                     <div class="blacklist-infos">
                    <h2><%= blacklist.name %></h2>
                  </div>
              </div>
           </div>
         </label>
        <% end %>
      </div>
    </div>
    <%= f.submit "Create profile", class: "btn btn-ghost" %>
   <% end %>
  </div>
</div>

<!-- swap divs JS function -->

<script type="text/javascript">
function SwapDivsWithClick(div1,div2)
{
   d1 = document.getElementById(div1);
   d2 = document.getElementById(div2);
   if( d2.style.display == "none" )
   {
      d1.style.display = "none";
      d2.style.display = "block";
   }
   else
   {
      d1.style.display = "block";
      d2.style.display = "none";
   }
}
</script>

app/views/pages/test.html.erb
<div class="dashboard-layout">
  <main class="dashboard-layout-main">
    <aside class="dashboard-sidebar">
      <div class="dashboard-sidebar-container">
        <div class="tab">
          <button class="tablinks" data-id="BlockedWebsites"> Blocked Websites</button>
          <button class="tablinks" data-id="Learning"> Learning Topics </button>
        </div>
      </div>
    </aside>
    <div class="dashboard-layout-right">
      <div id="BlockedWebsites" class="tabcontent d-none">
        <h1 style= 'font-family: Noto Serif JP; padding-bottom: 20px;'> <%= @user.first_name %>'s Blocked Websites </h1>

          <div class= "card-container-dashboard">
            <div class="card-product-dashboard">
              <img src="assets/facebook.png" />
              <div class="card-product-infos">
                <h2>Facebook</h2>
              </div>
            </div>

            <div class="card-product-dashboard">
              <img src="assets/twitter.png" />
              <div class="card-product-infos">
                <h2>Twitter</h2>
              </div>
            </div>

            <div class="card-product-dashboard">
              <img src="assets/bbcnews.png" />
              <div class="card-product-infos">
                <h2>BBC News</h2>
              </div>
            </div>

            <div class="card-product-dashboard">
              <img src="assets/instagram.png" />
              <div class="card-product-infos">
                <h2>Instgram</h2>
              </div>
            </div>
          </div>
        <div style="margin-top: 30px;">
        <%= link_to "Edit Blocked Websites", blacklist_users_edit_path, class: "btn btn-info btn-xs" %>
        </div>
      </div>
      <div id="Learning" class="tabcontent d-none">
        <h1 style= 'font-family: Noto Serif JP'> <%= @user.first_name %> here are your learning topics </h1>
          <div class= "card-container-dashboard">
            <div class="card-product-dashboard" style="width: 500px;">
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png"/>
              <div class="card-product-infos">
                <h2>Le Wagon</h2>
                <p>Change your life, learn to code</p>
              </div>
            </div>
          </div>
        <div style="margin-top: 30px;">
          <% if  FlashcardUser.count == 0 %>
          <%= link_to "Go to your flashcards", flashcard_path(Flashcard.first), class: "btn btn-info btn-xs" %>
          <% elsif  ((FlashcardUser.last.flashcard_id + 1) % 4) != 0 %>
          <%= link_to "Go to your flashcards", flashcard_path(FlashcardUser.last.flashcard_id + 1), class: "btn btn-info btn-xs" %>
          <% else %>
          <%= link_to "Go to your flashcards", flashcard_path(FlashcardUser.last.flashcard_id + 2), class: "btn btn-info btn-xs" %>
          <% end %>
        <%= link_to "Edit Your Learning Topics", blacklist_users_learn_path, class: "btn btn-info btn-xs" %>
        </div>
      </div>
    </div>
  </main>
</div>